//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayitlar
    {
        public int kayit_id { get; set; }
        public int kullanici_id { get; set; }
        public int kitap_id { get; set; }
        public System.DateTime alis_tarih { get; set; }
        public System.DateTime son_tarih { get; set; }
        public bool durum { get; set; }
        public string ceza { get; set; }
    
        public virtual kullanicilar kullanicilar { get; set; }
        public virtual kaynaklar kaynaklar { get; set; }
    }
}
